### ISSUE TITLE
Demo project

### ISSUE THREAD

**Issue by semsion** [Cycling74/rnbo.unity.audioplugin#21]
How is the demo project loaded!? 

Ref https://cycling74-assets.nyc3.digitaloceanspaces.com/rnbo/unity/example-projects/RNBODrumkit.zip

If going from the step in the link below, where you install via the package.json files from \TestProject\Packages\RNBOTypes and TestOrbs, we don't appear to be getting the whole project.

https://github.com/Cycling74/rnbo.unity.audioplugin/blob/main/docs/GETTING_STARTED.md 

It appears that maybe it's just a Visual Studio project which is loaded and built, however after trying this the project didn't build, and threw a lot of errors.

It seems as though the steps from the link above are possibly orientated more towards once you have exported a basic plugin that you want to load inside of Unity.

**Comment by jinpavg** [comment]
Hi @semsion , thank you for reaching out. 

Could you share a little more about what you are trying to do? You shouldn't need to install any packages in the RNBODrumkit Test Project -- the packages are already included.

Thanks for checking this out!

**Comment by jinpavg** [comment]
A thought I had -- when you say "how is the demo project loaded," I'm wondering if you mean how to open it in Unity? If so, I can help with that. You'll want to follow these steps:

1. Download the project
2. Open up Unity Hub
3. Select "Open", navigate to the `/TestProject` directory (this is the actual Unity Project folder)
4. You might be prompted to download a specific version of Unity and/or switch target platforms, depending on your setup

Let me know if this helps you get started or if you are having a different issue.

**Comment by jinpavg** [comment]
Hi @semsion , okay, cool!

And yes -- this RNBO DrumKit in particular was built with Unity 2021.3.11f1, but the RNBO/Unity integration itself should work with newer versions of Unity as well. For example, I've also been using it with 2022.2.15f1.

I'll close this ticket for now, best of luck and enjoy!

**Comment by semsion** [comment]
@jinpavg Ok great; thank you for the clarification!
