### ISSUE TITLE
Can Cycling74 confirm if this library will continue to be developed until in a stable state!?

### ISSUE THREAD

**Issue by semsion** [Cycling74/rnbo.unity.audioplugin#27]
As someone that was beginning to develop against RNBO with Unity, in the hope to use both together in a commercial project; can Cycling74 confirm if this library will continue to be developed until it's in a stable state!?

This is asked because there appears to be a number of instabilities in the library so far.

Any information would be gratefully received!

**Comment by jinpavg** [comment]
Hi @semsion, we are indeed working on closing the issues currently active on this repo, and aspire for the tool to be truly useful for RNBO users. Please note, though, that this tool remains in an experimental state, and we'd urge some caution in using it in a commercial product. That said, if you find any issues while doing your work, please do share them here! We'd like to address them.

**Comment by semsion** [comment]
Hey @jinpavg; great, that's good to know. Hopefully the more stable state will not differ too much from the current API. If you think that will be the case, please report back.

Will also come back here if find any anomalies.

**Comment by jinpavg** [comment]
Hi @semsion -- thank you for this. We say in the README that _This is experimental software—use at your own risk, and know that anything in this repository could change in the future._ I think this is good to keep in mind. Truly anything could still change as we develop this tool.

That being said, we'd be very interested to know what aspects of the current system work well for you, what you are relying on, what is a pain point, etc. This feedback will be very helpful to us and can help us understand the impact of changes we make.

**Comment by semsion** [comment]
Thank you for your response.

Will try and get some helpful discussion up and running!
