### ISSUE TITLE
MIDI output in Android

### ISSUE THREAD

**Issue by semsion** [Cycling74/rnbo.unity.audioplugin#28]
Had MIDI output in Android been implemented!?

I'm looking at possibly using this plugin to create a MIDI controller, ie to control external hardware / software via an Android device (USB / Bluetooth MIDI).

**Comment by x37v** [comment]
@semsion we don't yet have MIDI out from the audio plugin but after that, the hardware interfacing, would be up to you as that is likely beyond the scope of the audio plugin.

If you don't need the Unity game engine specifically, you could look into the Juce App template: https://github.com/Cycling74/rnbo.example.juce
it might be quicker to get to MIDI out with that.

**Comment by semsion** [comment]
Thanks @x37v ; yes there does also appear to be some possible MIDI plugins already for Unity.

Think they'll be quite a lot to deal with on the Android side, so may have to rethink my strategy. 

Could maybe look at the linked plugin also if that might make it easier.
