### ISSUE TITLE
Unity unable to add package: com.cycling74.rnbotypes@0.0.1 cannot be found

### ISSUE THREAD

**Issue by arokhsar** [Cycling74/rnbo.unity.audioplugin#3]
I get the following error in Unity when I attempt to add the package.json file generated by the build process via the package manager:

[Package Manager Window] Cannot perform upm operation: Unable to add package [file:/Users/rokhsar/Aria/RNBO/rnbo.unity.audioplugin-main/build/MyCustomPlugin]:
  Package com.cycling74.mycustomplugin@file:/Users/rokhsar/Aria/RNBO/rnbo.unity.audioplugin-main/build/MyCustomPlugin has invalid dependencies or related test packages:
    com.cycling74.rnbotypes (dependency): Package [com.cycling74.rnbotypes@0.0.1] cannot be found [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:356)

I'm on a MacBook Pro, M2, OS 13.2.1. Unity version is 2021.3.21f1.

The contents of my package.json file are:

{
  "name": "com.cycling74.mycustomplugin",
  "version": "0.0.1",
  "displayName": "My Custom Plugin",
  "unity": "2017.1",
  "licensesUrl": "https://support.cycling74.com/hc/en-us/articles/10730031661587",
  "dependencies": { 
      "com.cycling74.rnbotypes": "0.0.1"
  },
  "keywords": [
    "rnbo",
    "audio",
    "native_audio_plugin"
  ]
}

See below if you want to try it with my RNBO patch:

<pre><code>
----------begin_max5_patcher----------
3439.3oc6c10baaiEF9Z6eEXzMY2LItDjRVV6UMai2YbmoIdha5dQmNZnjfi
YKEoVRJamzo929d..+VfRTRzNVouWzXW9E.dO.GbH3yA9OO9ndSBuWD2i8uX
+J6ni9yiO5H0gjG3nz++i5M289o9twpKqWf3tvI+duWoOUh39D0gCWl7.yN6
vdyzGbxu+Z69YGLX4bu.eQh54vKNHcqYG0J8nKbSldiWvmFGIllnqcmwOw5U
Ltk5G8cj+qM8ureK8VhBlD5EbcXZUOstSEfPLK9hf3D2fohKRufzR+ndtQeJ
vctVANpzsQMg.d9AyOJcCIIQuO5xnvEkeNzIl48IQrVKh8nGpOKVDjvRBY51
G6NujaXdAyD2mqSpxI102ysbqWULxikYXxZixSDKRRbm3Kpe8zQmdigS3Euv
MxcdsiNSrfTV2Dwr5Wtz.Uqkk74EhRsqdom3uN9UEZE0p1rZYaTsRkGpivDQ
Tux0wqcW5mPVnZ0m8Pw3cuhkqNqz.l6FLyMIL5ypRdUUaZ374TWjcU2nwMwB
V3shHV1S5YuFE+44SBM0CZtHwcWEh2v9wqd+6XWGFMmtbwLVbRD46fTkfDWu
.4uJe7jsvUdQLorM4yrjaDLw8KBij2xzvYhCF4akwH+hq+R8UT5b9tSD9pC9
Sos9x2HUE7c+bXzLpKKcMN4ljiqZZnw1KVljOCQUqiz0opDjNKa1gw96jLs5
9trxqzotIrt+pYgS+iTMLuUkasjtaJZPEG9Fg+h7libxrd4SQHs5u+5UOgZN
Qy2S3BQjbneYCYOZjZrWXvEpplyv98GMh6LJ+ocia.INWJm4SDcw6KbZjYKT
SwMllvMxcrbbg2jkIEybkMeWIuJ4xT9vqd8L7DWF38+VJxlxlZFiqNus5hhE
Qdt9km4VcXCZvwYcinRoChofaJlBmtIlB9nuchofiXJPLEHlBDSAhoncNIQL
EO8wT3zPLE1O1wTbqaT9S7KSmd07vvDYv.uM7tfUh6PMPhU+xXeOEpAiS+vk
5HYYw99akCQne8DSgnXYLDEaignX2bHJCO8TYXIN8sU+fauRPJ5mS13ieUZg
n+6QKFlay7KrKtUuhFNRdOSHyNS+fZZtY6Cu4lWwwokQOmWj19+k5s+FcelO
iVfb5HeuuHl0Rq.uQqftuawC7D1tOU0SRfhox8phRjHVjrqRwGj2LSOfmlwn
o9l6kfv2+9ZSH+38VW+gcs8+t7mfVDDITnepV+Ie86On8rs0cHxbzuKNnjQC
vBuVEHWtfb.+BDqDcWgenKys2pPfZ+6XHHkeW02ORwI6FvjOBYzLT2NcrSO+
iS12KNwnNdN0VzNyiWi27SM79Ij2l46tT9S5aeW7UIK5dGRyYl1VWi9xMpuO
hZKul1lFM+7UpoGrApraht686UmZ8suacpcu+YZmZtY8MUpZVesMpuOhZaSc
pWold.zotCEc4R5DrGKq1USc8EZcOlk8vn3L8+buuAdMGyB84YZVyJ8vUU53
Dwh3cUleq2sdyDpX2zQUPwySA06ltNvx35npvzHJnGltf9l8kLupVyqtze1p
Re5krOQO+F17vHAKR3NSpAL4yRs7nUBmlrJpX.um9c4x08g28ueOSFRsXKCC
r5R3c3r1ouUWsqG28Jyt1uQiz6d9YjZXpix8pN7W068vxsLvKY2MY55qbIJl
IHOXdSzt4jOzUdc0Na70Ajg4iR0cMFjAqZPRB2lkOwrg4GBCtUDkDSywPim7
quFJpkThNaQAo9hRmz6PdcC94PVoUMhllORDK+FDqS9sVU9uNJbdmZ.BLsTV
p..jl.2oIKW0.cXaI9OjDt01hQqZJxO2tXAdu7lktbt6Fuo2juBp0D5X1cd9
9Lxsk5iyQgmwBCXKzeXJlen6rSX+rLtM0SaJ49htT0hD4MkNXp+O52+Gu3Zu
n3jWPd3lwdguK8q+yuE7pYNLtOPprbxZkHutAX1MFpPWZbyMpoly3aBuisbg
ZBGlbAxjyEQuVSoK7u4l0Wu1vH1nY0v2.hF+LyaOhk3J596puywSkNOIb8pb
RTkVQoWCR1XuX8wFXHVsoI96wZGdwauPwIRTnuO0qO8kOo4gROHEslWbwPjS
N.eKzRqmhr09CEs12otzSVWm5SApNO2P0gOzzGWbQK+zpMrZLgTHYIL2Yyzc
3yiHV8xJpGM6We64W9gy+g27ym+V1qYe7pyYee5YrHeTwIz6n9aOyFev2A+S
W65GKL7kJ2OA9MqQYO4aXm5WDL0e4LA4WmcoV.WSGa99AgV8IHWyByUXXtrZ
ruaMXYup45ScBP1xZ1FI+XK3b6.Ty11JU6niX8ZVEH.0iTLQAX0yTEAtpmay
b.9Zd+9Cr5aM5z9qiDPqcfDvBOV4nhs5KxWvHXs0Tt3DYLDTbj7XtrNIuUks
lYEWU4neyqA4ezfR2ZtGfh2rZkU7wDKi0p4EOlWWT2K80f3mXsI5GaB2v1mV
EZ6+iFCjebQKHf7iKZj+Qi3Ox6V7Gs5q3d7ry.9i.+Qf+HveD3OB7GA9i.+Q
f+HveD3OB7GA9i.+Qf+HveD3OB7GA9i.+Qf+HveD3OB7GA9i.+Qf+HveD3OB
7GA9i.+Qf+HveD3OB7GA9i.+Qf+3SL9iEjF198+wNB9wbzFi8kejDNiaYBaQ
aiXK5XDaQdyXKNvNcKkVgs3fQsfZwJDKtwNhodE1n5qZsiq1zZO3op6ta2Pu
kQbJAK87faE9zXYCFA9ntY28NyHLbfZW9lOz3968Fk5sZeNU17FWsQrUae5x
6uCE7WR9DFXRhOaKvycc8y6OTimqd2I04qV+7WNtZyp8h9K6P496dfwsOyjd
OrizacWZm9ptz5+c85c51kbUUuhz8c58l2hpX60tuqK2s+oG6hXxd+.0OxjD
dZ2Jg5+dBclUm2kct7ko0yFuQuyYM4wUagagG5rmPmmd.+WufYg2cEErPyYG
Pw0nSN.6rjCvteV1AXOHuUQA3HlFtTG4fsAKb+tImA5ORMe6.t1zpRY.mgHk
APJCfTF.oL.RY.jx.HkAPJCfTF.oL.RY.jx.HkAPJCfTF.oL.RY.jx.HkAPJ
CfTF.oL.RY.jx.HkAPJCfTF.oL.RY.jx.HkAPJCfTF.oL.RY.jx.HkAPJCfT
F3wNkAVk9vZLQ57zkw.eQDEd+XE4hOTlmwxnK5zMvo1mqQ58TEAibKmt.v2x
0+wUqssGzzxOjtk0T24KLt+XWC2z5WViaG0Vl1Op4cz9Qs8H09QMejF3cC4T
.fKEvkB3RAbo.tT.WJfKEvkB3RAbo.tT.WJfKEvkB3RAbo.tT.WJfKEvkB3R
Abo.tT.WJfKEvkB3RAbo.tT.WJfKEvkB3RAbo.tT.WJfKEvkB3R6d3RaB2vZ
nP1+QmuzlXfrXSxdMDP9wEMx+nQ7Gs5V7GGn1WqsG0G3OB7GA9i.+Qf+HveD
3OB7GA9i.+Qf+HveD3OB7GA9i.+Qf+HveD3OB7GA9i.+Qf+HveD3OB7GA9i.
+Qf+HveD3OB7GA9i.+Qf+HveD3OB7GA9iOw3OVPZXM3GG7zs4ZF6K+HIbVAg
hkvVbnQpEc11cUSpCnhSQ8e42GLpy+S9dpSgM+26cYicbkVVMk2dM+odWdyc
nxKceRwaJwJ87faE9zHYClfSMZB3FMAVqAbzparo11qXCZkPWLxXSRcZqabk
1P6E6zauyo78R58RHk4h.x2M45tYReqcgUn80dPNsuNNFrYC5HXesT1LNWuW
mZwAru.1W.6Kf8Ev9BXeAru.1W.6Kf8Ev9BXeAru.1W.6Kf8Ev9BXeAru.1W
.6Kf8Ev9BXeAru.1W.6Kf8Ev9BXeAru.1W.6Kf8Ev9BXeAru.1W.66SCruM.
bXMRHO8oC32EB2+fpWOXFcw9aA5hal3W9vyj+3Lqsl32JxXVUdbkZXMIjuFI
L896PU7kOP83FXP.c5VATC8Y+VHfwdeJPpDMKiuTKfNau.9xtT57BdfYaP4r
MpbVaqxclVwT6StNC1McqKglkJP9thnmttwjtYYJIgcmWhbg1lItOWC2y37r
dpg2KUvWMjXUyZWiHVKOM8MSOXf1akFvlHxaZ3746AdBzfJ5chCuUtDcoOoC
k2EFKkvyskRvoUuv019NEJGnM6GY+bbV6ip2a2hsmlRyXj8kOd0YTKel1DU+
vSsrFNjyWWP87cHn9RtOLER7lBvkZFiqL2c6ioPp.caPEbSa79cSPE7Q+MIn
BNBp.AUffJPPEHnhc2wIBpnSBpfu8oMbsfJTJaOeu.Qd+AcLFpo3kGuZjFwg
KillMGdZZhyJlleF0SvKvMQRYSw0bp9ZLFKSaKmAsnb5SWCeOKm9snbF1AsG
mV1dJEBUkDK4Qsf4NlKYq8pjssaSQOpCDWadKJIU0Ye6tXa01RxdeKoVTPON
ls1zBeT5pxOqMcXF1AlQdabiw6B+XYOjM2gYuKo13JqlD2QcYZWQ6nMbcbeF
m11mYu0WdKmpXeG4ysZYAs2iB9Z4hoUtqc1rKFczLtKVjFFmpXkEJ89b+tNR
uyd0w5reU++p1Gg5EIt0K65U6cO8bildiWhXZxxHcbS2ep9ypQu5FUvAK8RK
aUTZEQYRubftkoh8p2w+0w+e.LxhEyA
-----------end_max5_patcher-----------
</code></pre>

**Comment by x37v** [comment]
@arokhsar did you add `RNBOTypes` ? https://github.com/Cycling74/rnbo.unity.audioplugin/blob/main/docs/GETTING_STARTED.md#installation

**Comment by arokhsar** [comment]
I did not! It works now. In my opinion, that section of Getting Started makes it sound like installing the custom plugin installs both itself and RNBOTypes packages when it says "This should result in the RNBO Unity Types package and the package named with the name you chose for your RNBO plugin added to the Installed Packages for your project."

But could be my own reading problem. Thank you for your help!
