### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by semsion** [Cycling74/rnbo.unity.audioplugin#30]
Is this library using JUCE under the hood? If so how does the licensing work in this regard!?

**Comment by semsion** [comment]
After having another look through the source, that doesn't seem to be case, which is great, as the JUCE licensing model certainly seems to be in opposition to the one provided by Unity. 

If there's any more information to add, please do.

**Comment by jinpavg** [comment]
Hi @semsion, that's right -- this plugin does not use JUCE. The relevant licenses would be the MIT license on this repo, and the [Cycling '74 License for Max-Generated Code for Export](https://support.cycling74.com/hc/en-us/articles/10730031661587-Cycling-74-License-for-Max-Generated-Code-for-Export).

**Comment by semsion** [comment]
Hey @jinpavg - wonderful stuff; thanks for the clarification!
