### ISSUE TITLE
Unity crash when playing scene with RNBO plugin

### ISSUE THREAD

**Issue by JimPapanick** [Cycling74/rnbo.unity.audioplugin#34]
I am aiming at creating simple and custom plugins to run in a mini game for Windows.
Whenever I run the scene to test my sounds, Unity crashes. 

I am following this tutorial here so you can imagine my setup exactly the same as his. (The plugin export/setup starts at the 8m mark)
https://www.youtube.com/watch?v=OBRRrwvZ_mo

In the Crashes folder I find these two files:

[crash.dmp](https://github.com/Cycling74/rnbo.unity.audioplugin/files/13718895/crash.dmp)

[Editor.log](https://github.com/Cycling74/rnbo.unity.audioplugin/files/13718896/Editor.log)

Stuff I  have tested:

-Build a simpler plugin (still crashes)
-Turn off the object attached with the Audio Source routed to the Mixer with the plugin (doesn't crash)

**Comment by x37v** [comment]
@JimPapanick one question is.. the tutorial you reference, it doesn't actually use this `rnbo.unity.audioplugin` but instead our older JUCE based export.. which are you using?

**Comment by JimPapanick** [comment]
> @JimPapanick one question is.. the tutorial you reference, it doesn't actually use this `rnbo.unity.audioplugin` but instead our older JUCE based export.. which are you using?

I followed your newer export style by using 
```
mkdir build
cd build
cmake .. -DPLUGIN_NAME="My Custom Plugin"
cmake --build . --config Release
```
It made a new .dll which I imported in my Unity's project folder. The parameters were shown just fine but as soon as I play the scene, it still crashes.

**Comment by JimPapanick** [comment]
I have followed the steps and it works. I will update for further errors.
