### ISSUE TITLE
Plugin turns inputs into Mono even though it has 2 outputs

### ISSUE THREAD

**Issue by JimPapanick** [Cycling74/rnbo.unity.audioplugin#35]
In Unity, I have a sound source in an empty room and I want to have sound coming out of it and be directional, if the player turns right it should be more on their right speaker etc.
However 
When the Audio Mixer bypasses my plugin it plays Stereo as it should. But when I run it through plugin it turns into Mono.
![image](https://github.com/Cycling74/rnbo.unity.audioplugin/assets/149523020/828ff6d7-4eca-484f-99e5-b6773bc617e4)

Plugin looks like this: 
![image](https://github.com/Cycling74/rnbo.unity.audioplugin/assets/149523020/5a4eb52b-b9c1-4283-a3c1-a1468efe6625)

What am I missing?

**Comment by x37v** [comment]
> What am I missing?

your patch is only listening to 1 channel.. see the `[in~ 1]` at the top?

**Comment by JimPapanick** [comment]
You are right! It takes a stereo signal and only reads one of the channels.... How did I miss this.

Thanks
