### ISSUE TITLE
Unity not creating .dll files on compile

### ISSUE THREAD

**Issue by Buckblack2** [Cycling74/rnbo.unity.audioplugin#42]
Hi everyone,

I'm having an issue sharing my custom Unity audio plugin with my team. Everything works fine on my computer: when I import the RNBO types and my custom packages into Unity it makes all of the necessary .dll files when it compiles. On my teams' Windows machines (I'm on Mac) the Unity project is not making the .dll files for me when compiling. Any ideas why this is occurring? I've attached an image of the error my team is getting when trying to install and use my custom package. 
<img width="1021" alt="DLLnotfoundexception" src="https://github.com/Cycling74/rnbo.unity.audioplugin/assets/123770246/f45b3a37-e111-4533-b6dc-1f10972f81e4">

**Comment by jinpavg** [comment]
Hi @Buckblack2, thank you for your patience here. 

I've got Unity 2021.3.23f1 working with RNBO on Windows here. Perhaps you could send me one of your plugins, and I can see if I can reproduce the issue? Are you able to reproduce this yourself on a windows machine? 

If you could, please share any more info you can, for example, RNBO version, Unity version, OS version for yourself on the Mac and your team on Windows.

**Comment by Buckblack2** [comment]
Hi @jinpavg, thanks for your response.

Attatched here is a rough version of the generative music plugin I made. I'm also using the RNBOTypes package form this GitHub repo as directed in the documentation. 

My team is using Unity version 2023.2.9f1 and I'm using RNBO version 1.2.4 and MacOS Sonoma 14.3.1. I'll contact my team about what versions of Windows they have and comment that info a soon as I have it.

[chordbassdemo.zip](https://github.com/Cycling74/rnbo.unity.audioplugin/files/14874262/chordbassdemo.zip)

**Comment by Buckblack2** [comment]
We have two people using Windows 10 and two others using Windows 11.

**Comment by Buckblack2** [comment]
Hey @jinpavg, just wanted to follow up on this. Thanks!

**Comment by jinpavg** [comment]
Hi @Buckblack2 , thank you for the ping here, I appreciate the reminder. 

I've given this a look today, thank you, and I think I understand what you are asking -- it looks like the plugin you've shared includes only the macOS-built version of the plugin (in the `Assets/Plugins/Darwin/` directory). 

Now I think I might understand your question better -- you are asking why the Windows version (the .dll) is not present. When you say "Unity project is not making the .dll files for me when compiling" -- I think this is the root of the issue. Unity won't create the Windows version of the plugin for you, instead you (or your team) will have to set up a Windows machine to build according to the build instructions in [the README](https://github.com/Cycling74/rnbo.unity.audioplugin/blob/main/README.md#building-for-windows)

Then, once you've built the Windows version of the plugin, you can copy the resulting `Windows` folder from inside `Assets/Plugins` in the plugin package you've built and paste it in `Assets/Plugins` alongside your `/Darwin` folder. Now, your plugin should have support for both macOS and Windows.

Does this make sense? Let me know if this helps or if I've misunderstood the situation.
