### ISSUE TITLE
Feature Request: expand data types for inport

### ISSUE THREAD

**Issue by arokhsar** [Cycling74/rnbo.unity.audioplugin#6]
Right now, the SendMessage method of the handle only takes a double as a valid data type. It would be great to expand that to include arrays/lists and strings as well.

**Comment by x37v** [comment]
The helper should already support the message types that rnbo supports?

```cs
    public bool SendBang(MessageTag tag, MillisecondTime atTime = 0);
    public bool SendMessage(MessageTag tag, Float value, MillisecondTime atTime = 0);
    public bool SendMessage(MessageTag tag, Float[] values, MillisecondTime atTime = 0);
```

RNBO doesn't have string support though so I'm not quite sure what you mean by that.
If you want to use a list you should be able to do `SendMessage(tag, list.ToArray());`

**Comment by arokhsar** [comment]
That's great -- I didn't know it already supported Float[], which is what I wanted most. Thank you!
